apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "~0.13.x" # Uses the latest in the 0.13.x series
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  values: {} # Empty - all configuration is in the production overlay
