apiVersion: v1
kind: Secret
metadata:
  name: wireguard-config
  namespace: wireguard
stringData:
  wg0.conf: |
    [Interface]
    PrivateKey = ${WG_PRIVATE_KEY}
    Address = ${WG_CLIENT_IP}
    ListenPort = ${WG_CLIENT_PORT}
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport ${MC_PORT} -j DNAT --to-destination ${NODE3_IP}:${MC_PORT}
    PostUp = iptables -t nat -A PREROUTING -i %i -p udp --dport ${MC_PORT} -j DNAT --to-destination ${NODE3_IP}:${MC_PORT}
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport ${MC_PORT} -j DNAT --to-destination ${NODE3_IP}:${MC_PORT}
    PostDown = iptables -t nat -D PREROUTING -i %i -p udp --dport ${MC_PORT} -j DNAT --to-destination ${NODE3_IP}:${MC_PORT}

    [Peer]
    PublicKey = ${VPS_PUBLIC_KEY}
    # Endpoint = ${VPS_ENDPOINT}
    AllowedIPs = 172.16.0.1/32
    PersistentKeepalive = 25
