apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'vps-node-exporter'
            static_configs:
              - targets: ['wireguard.wireguard.svc:9100']
            metrics_path: /metrics
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - stats.xzr.es
        path: /
      persistence:
        enabled: true
        size: 10Gi
        accessModes: ["ReadWriteOnce"]
