apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'vps-node-exporter'
            static_configs:
              - targets: ['wireguard.wireguard.svc:9100']
            metrics_path: /metrics
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: local-path
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - stats.xzr.es
        path: /
      persistence:
        enabled: true
        storageClassName: local-path
        size: 10Gi
        accessModes: ["ReadWriteOnce"]
