apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    nodeExporter:
      serviceMonitor:
        relabelings:
          - action: replace
            sourceLabels: [__meta_kubernetes_node_name]
            targetLabel: instance
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'vps-node-exporter'
            static_configs:
              - targets: ['wireguard.wireguard.svc:9100']
                labels:
                  instance: 'Gateway VPS'
            metrics_path: /metrics
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      initChownData:
        enabled: false
      podSecurityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - stats.xzr.es
        path: /
      persistence:
        enabled: true
        storageClassName: local-path
        size: 10Gi
        accessModes: ["ReadWriteOnce"]
