---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.14.x"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    expose:
      type: clusterIP
      tls:
        enabled: false
    database:
      type: internal
    redis:
      type: internal
    externalURL: http://hub.xzr.es
    harborAdminPassword: Harbor@12345
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          storageClass: "local-storage"
          accessMode: ReadWriteOnce
          size: 30Gi
        jobservice:
          jobLog:
            storageClass: "local-storage"
            accessMode: ReadWriteOnce
            size: 1Gi
        database:
          storageClass: "local-storage"
          accessMode: ReadWriteOnce
          size: 5Gi
        redis:
          storageClass: "local-storage"
          accessMode: ReadWriteOnce
          size: 1Gi
        trivy:
          storageClass: "local-storage"
          accessMode: ReadWriteOnce
          size: 5Gi
    registry:
      relativeurls: true
    nginx:
      clientMaxBodySize: 0
    nodeSelector:
      kubernetes.io/hostname: node2
