apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: authentik
      version: "2024.10.5"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 10m
  values:
    global:
      podAnnotations:
        fluxcd.io/automated: "true"
    authentik:
      log_level: info
      error_reporting:
        enabled: false
      postgresql:
        host: "192.168.1.11"
        port: 5432
        name: "authentik"
        user: "authentik"
      redis:
        host: "authentik-redis-master"
        port: 6379
    postgresql:
      enabled: false
    redis:
      enabled: true
      image:
        tag: "7.4.2-debian-12-r0"
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 1Gi
    server:
      replicas: 1
      envFrom:
        - secretRef:
            name: authentik-secret
    worker:
      replicas: 1
      envFrom:
        - secretRef:
            name: authentik-secret
