apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      version: "2024.10.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_POSTGRESQL__PASSWORD
      targetPath: authentik.postgresql.password
  values:
    authentik:
      postgresql:
        host: "192.168.1.11"
        user: "authentik"
        name: "authentik"
    postgresql:
      enabled: false
    redis:
      enabled: true
      auth:
        enabled: false
