apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - auth.xzr.es
      paths:
        - /
