apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    authentik:
      authentik_host: "https://auth.xzr.es"
    
    server:
      env:
        - name: AUTHENTIK_CSRF_TRUSTED_ORIGINS
          value: "https://auth.xzr.es"
        - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
          value: "0.0.0.0/0"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - auth.xzr.es
    
    worker:
      env:
        - name: AUTHENTIK_CSRF_TRUSTED_ORIGINS
          value: "https://auth.xzr.es"
        - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
          value: "0.0.0.0/0"