apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      version: "2024.10.5"
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.xzr.es
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.xzr.es
