apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.19.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    routingMode: tunnel
    tunnelProtocol: vxlan
    ipam:
      mode: kubernetes
    mtu: 1400
    kubeProxyReplacement: true
    gatewayAPI:
      enabled: true
    l2announcements:
      enabled: true
    l2NeighDiscovery:
      enabled: true
    externalIPs:
      enabled: true
    encryption:
      enabled: true
      type: ipsec
      ipsec:
        keyFile: keys
    authentication:
      enabled: true
      mutual:
        spire:
          enabled: true
          install:
            enabled: true
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
