apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  targetNamespace: nginx-ingress
  chart:
    spec:
      version: "4.9.1"
  values:
    controller:
      allowSnippetAnnotations: true
      replicaCount: 4
      service:
        type: LoadBalancer
        #annotations:
        #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    prometheus:
      create: true
