apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress # Chart will be installed in this namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "~4.x.x"      # Uses the latest in the 4.x series
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
