apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress # Chart will be installed in this namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "~4.x.x"      # Uses the latest in the 4.x series
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
  values:
    controller:
      # Basic settings good for any environment
      replicaCount: 1
      service:
        type: LoadBalancer   # Use 'NodePort' if not on a cloud with LB
        loadBalancerIP: 192.168.1.240
        ports:
          - name: http
            port: 80
            targetPort: http
          - name: https
            port: 443
            targetPort: https
