apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  targetNamespace: nginx-gateway
  values:
    nginxGateway:
      replicaCount: 4
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    service:
      type: LoadBalancer
    prometheus:
      create: true
