apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/harbor
  - local-pv.yaml
  - httproute.yaml

patches:
  - path: helmrelease.yaml
    target:
      kind: HelmRelease
      name: harbor
